/**
 * QuickOrder 商用プラン設計
 * 大手モバイルオーダー（定額＋初期費用＋席数制限）に対抗しつつ
 * Growth を主力にアップセルしやすい階段構造。
 */
export const PRODUCT = {
  name: 'QuickOrder',
  tagline: '席のQRから厨房まで。飲食店の注文オペレーションを一本化',
  currency: 'JPY',
  trialDays: 14,
  /** 年払い割引（月額×10 = 2ヶ月分無料） */
  annualMultiplier: 10,
  /** LP既定を年払いにして ACV を上げる */
  defaultBillingCycle: 'annual',
  /** 追加店舗（Growth以上） */
  extraStoreMonthly: 9800,
  /** Stripe Payment Link（空なら見積もりCTAのみ） */
  stripePaymentLink: '',
  successPath: 'admin.html?billing=success',
  /** LP希少性（運用で更新可） */
  introSlotsRemaining: 7,
  introSlotsLabel: '今月の優先導入枠',
  competitorNote: '大手は月額1〜3万円＋初期10万円超が一般的。QuickOrderは決済形・POS形・予約/会員・チャネルまで段階搭載（実決済は後日接続）。',
};

/**
 * @typedef {'lite'|'growth'|'business'|'chain'} PlanId
 */

/** @type {Array<{
 *  id: PlanId,
 *  name: string,
 *  badge?: string,
 *  tagline: string,
 *  priceMonthly: number,
 *  priceSetup: number,
 *  maxTables: number | null,
 *  maxStores: number | null,
 *  orderFeePercent: number,
 *  highlights: string[],
 *  features: Record<string, boolean|string|number>,
 *  cta: string,
 *  recommended?: boolean,
 * }>} */
export const PLANS = [
  {
    id: 'lite',
    name: 'Lite',
    tagline: '個人店・はじめてのモバイルオーダー',
    priceMonthly: 6980,
    priceSetup: 29800,
    maxTables: 15,
    maxStores: 1,
    orderFeePercent: 0,
    highlights: [
      '客席QR注文・カート・ステータス',
      '厨房リアルタイムモニター',
      'メニュー編集・テーブルPIN',
      'テーブル状況ボード',
      'メールサポート',
    ],
    features: {
      menuEdit: true,
      kitchenMonitor: true,
      tablePin: true,
      allergenFilter: true,
      analytics: false,
      multiLang: false,
      brandCustom: false,
      soundAlert: false,
      slaTimer: false,
      multiStore: false,
      prioritySupport: false,
      exportCsv: false,
      inventory: false,
      coupons: false,
      kdsModes: false,
      kitchenTickets: false,
      staffRoles: false,
      serviceCharge: false,
      tableBoard: true,
      tip: false,
      payments: true,
      takeout: true,
      delivery: false,
      reservations: false,
      waitlist: true,
      loyalty: false,
      posBridge: false,
      deepAnalytics: false,
      auditLog: false,
      autoPrint: false,
    },
    cta: 'Liteで相談する',
  },
  {
    id: 'growth',
    name: 'Growth',
    badge: '一番選ばれています',
    tagline: '回転率と客単価を伸ばす標準プラン',
    priceMonthly: 14800,
    priceSetup: 49800,
    maxTables: 50,
    maxStores: 1,
    orderFeePercent: 0,
    recommended: true,
    highlights: [
      'Liteの全機能',
      '売上分析・期間CSV',
      'クーポン（％/円）',
      '在庫数＆自動売切',
      'KDS表示切替・厨房伝票印刷',
      'サービス料設定・日英メニュー',
      '音付き厨房アラート',
    ],
    features: {
      menuEdit: true,
      kitchenMonitor: true,
      tablePin: true,
      allergenFilter: true,
      analytics: true,
      multiLang: true,
      brandCustom: false,
      soundAlert: true,
      slaTimer: false,
      multiStore: false,
      prioritySupport: true,
      exportCsv: true,
      inventory: true,
      coupons: true,
      kdsModes: true,
      kitchenTickets: true,
      staffRoles: false,
      serviceCharge: true,
      tableBoard: true,
      tip: true,
      payments: true,
      takeout: true,
      delivery: true,
      reservations: true,
      waitlist: true,
      loyalty: true,
      posBridge: false,
      deepAnalytics: false,
      auditLog: false,
      autoPrint: true,
    },
    cta: 'Growthで始める',
  },
  {
    id: 'business',
    name: 'Business',
    tagline: '繁忙店・複数端末・ブランド統制',
    priceMonthly: 29800,
    priceSetup: 98000,
    maxTables: null,
    maxStores: 3,
    orderFeePercent: 0,
    highlights: [
      'Growthの全機能',
      'テーブル数無制限・最大3店舗',
      'スタッフ権限（厨房/ホール/店長）',
      '配膳SLA・テーブル状況ボード',
      '店舗ブランディング・伝票印刷',
      '導入マネージャー付き',
    ],
    features: {
      menuEdit: true,
      kitchenMonitor: true,
      tablePin: true,
      allergenFilter: true,
      analytics: true,
      multiLang: true,
      brandCustom: true,
      soundAlert: true,
      slaTimer: true,
      multiStore: true,
      prioritySupport: true,
      exportCsv: true,
      inventory: true,
      coupons: true,
      kdsModes: true,
      kitchenTickets: true,
      staffRoles: true,
      serviceCharge: true,
      tableBoard: true,
      tip: true,
      payments: true,
      takeout: true,
      delivery: true,
      reservations: true,
      waitlist: true,
      loyalty: true,
      posBridge: true,
      deepAnalytics: true,
      auditLog: true,
      autoPrint: true,
    },
    cta: 'Businessを見積もる',
  },
  {
    id: 'chain',
    name: 'Chain',
    badge: '多店舗',
    tagline: 'チェーン・FC・本部一括管理',
    priceMonthly: 49800,
    priceSetup: 198000,
    maxTables: null,
    maxStores: null,
    orderFeePercent: 0.8,
    highlights: [
      'Businessの全機能',
      '店舗数無制限（追加店舗¥0）',
      '本部ダッシュボード・横断CSV',
      '注文手数料 0.8%',
      '全機能解放＋優先導入枠',
      'SLA・専任サポート・研修',
    ],
    features: {
      menuEdit: true,
      kitchenMonitor: true,
      tablePin: true,
      allergenFilter: true,
      analytics: true,
      multiLang: true,
      brandCustom: true,
      soundAlert: true,
      slaTimer: true,
      multiStore: true,
      prioritySupport: true,
      exportCsv: true,
      hqDashboard: true,
      inventory: true,
      coupons: true,
      kdsModes: true,
      kitchenTickets: true,
      staffRoles: true,
      serviceCharge: true,
      tableBoard: true,
      tip: true,
      payments: true,
      takeout: true,
      delivery: true,
      reservations: true,
      waitlist: true,
      loyalty: true,
      posBridge: true,
      deepAnalytics: true,
      auditLog: true,
      autoPrint: true,
      hqMenuSync: true,
    },
    cta: 'Chainを相談する',
  },
];

export const ADDONS = [
  { id: 'setup_rush', name: '特急導入（5営業日）', price: 19800, unit: '一式' },
  { id: 'menu_photo', name: 'メニュー撮影・入稿代行', price: 39800, unit: '一式' },
  { id: 'staff_training', name: 'スタッフ研修（現地2時間）', price: 24800, unit: '回' },
  { id: 'extra_store', name: '追加店舗', price: 9800, unit: '月' },
];

export const DEFAULT_SHOP = {
  name: 'QuickOrder',
  subtitle: 'モバイルオーダー',
  tableCount: 12,
  adminPin: '',
  subscribed: false,
  subscribedAt: null,
  /** トライアル開始・終了（未設定なら初回アクセスで付与） */
  trialStartedAt: null,
  trialEndsAt: null,
  planId: 'growth',
  billingCycle: 'annual',
  ownerEmail: '',
  ownerPhone: '',
  stores: 1,
  locale: 'ja',
  isOpen: true,
  hoursNote: '11:00–22:00',
  address: '',
  lastOrderEnabled: false,
  lastOrderTime: '21:30',
  /** Guest UX / industry features */
  accentColor: '#0D5C4D',
  minOrderAmount: 0,
  partySizeRequired: false,
  ageGateEnabled: true,
  quickServiceEnabled: true,
  /** Revenue-justifying ops features */
  serviceChargePercent: 0,
  tipEnabled: false,
  tipPresets: [0, 5, 10],
  coupons: [],
  /** itemId -> remaining stock (null/absent = unlimited) */
  stock: {},
  /** staff role PINs (Business+) */
  staffPins: { kitchen: '', floor: '', manager: '' },
  kdsMode: 'timeline', // timeline | byTable | byItem
  /** Enterprise parity */
  channelsEnabled: ['dine_in', 'takeout', 'delivery'],
  paymentMethodsEnabled: ['pay_at_register', 'card', 'paypay', 'transit'],
  posProvider: 'none',
  posLocationId: '',
  printerMode: 'browser',
  autoPrintOnOrder: false,
  printerIp: '',
  loyaltyEnabled: true,
  staffEmails: [],
};

/** @deprecated 互換用。Growth 月額を返す */
export const PRODUCT_LEGACY = {
  ...PRODUCT,
  priceMonthly: PLANS.find(p => p.id === 'growth').priceMonthly,
  priceSetup: PLANS.find(p => p.id === 'growth').priceSetup,
};
