const MENU_DATA = {
  categories: [
    { id: 'all', label: 'すべて', icon: '🍽️' },
    { id: 'rice', label: 'ご飯もの', icon: '🍚' },
    { id: 'noodle', label: 'めん類', icon: '🍜' },
    { id: 'side', label: 'サイドメニュー', icon: '🥗' },
    { id: 'drink', label: 'ドリンク', icon: '🥤' },
    { id: 'dessert', label: 'デザート', icon: '🍮' },
  ],

  allergens: [
    { id: 'gluten', label: '小麦', emoji: '🌾' },
    { id: 'egg', label: '卵', emoji: '🥚' },
    { id: 'dairy', label: '乳製品', emoji: '🥛' },
    { id: 'shrimp', label: 'えび', emoji: '🦐' },
    { id: 'peanut', label: 'ピーナッツ', emoji: '🥜' },
    { id: 'soy', label: '大豆', emoji: '🫘' },
  ],

  items: [
    {
      id: 'item_001',
      category: 'rice',
      name: '特製チキンカレー',
      description: '秘伝スパイスで仕上げた本格カレー。辛さ調整可能',
      price: 980,
      image: null,
      emoji: '🍛',
      popular: true,
      allergens: ['gluten', 'dairy'],
      customizable: [
        { id: 'spice', label: '辛さ', type: 'select', options: ['甘口', '中辛', '辛口', '激辛'], default: '中辛' },
        { id: 'rice_size', label: 'ライスの量', type: 'select', options: ['少なめ', '普通', '大盛り(+100円)'], default: '普通' },
      ],
    },
    {
      id: 'item_002',
      category: 'rice',
      name: '海鮮丼',
      description: '新鮮な海の幸を贅沢に盛り付けた一品',
      price: 1480,
      image: null,
      emoji: '🐟',
      popular: true,
      allergens: ['shrimp', 'soy'],
      customizable: [
        { id: 'rice_size', label: 'ライスの量', type: 'select', options: ['少なめ', '普通', '大盛り(+100円)'], default: '普通' },
      ],
    },
    {
      id: 'item_003',
      category: 'rice',
      name: '唐揚げ定食',
      description: 'ジューシーな唐揚げにご飯・味噌汁・小鉢付き',
      price: 1050,
      image: null,
      emoji: '🍗',
      popular: false,
      allergens: ['gluten', 'egg', 'soy'],
      customizable: [
        { id: 'rice_size', label: 'ライスの量', type: 'select', options: ['少なめ', '普通', '大盛り(+100円)'], default: '普通' },
      ],
    },
    {
      id: 'item_004',
      category: 'noodle',
      name: '濃厚醤油ラーメン',
      description: '豚骨と鶏がらのWスープに醤油を合わせた一杯',
      price: 850,
      image: null,
      emoji: '🍜',
      popular: true,
      allergens: ['gluten', 'soy', 'egg'],
      customizable: [
        { id: 'hardness', label: '麺の硬さ', type: 'select', options: ['やわらかめ', '普通', '硬め', 'バリ硬'], default: '普通' },
        { id: 'richness', label: '濃さ', type: 'select', options: ['薄め', '普通', '濃いめ'], default: '普通' },
        { id: 'extra_char_siu', label: 'チャーシュー追加', type: 'toggle', price: 200 },
      ],
    },
    {
      id: 'item_005',
      category: 'noodle',
      name: 'もちもちうどん',
      description: '讃岐直送の麺を使用。だしの旨味が染みる一杯',
      price: 750,
      image: null,
      emoji: '🍢',
      popular: false,
      allergens: ['gluten', 'soy'],
      customizable: [
        { id: 'topping', label: 'トッピング', type: 'select', options: ['なし', '温玉(+100円)', '天ぷら(+200円)', '両方(+280円)'], default: 'なし' },
        { id: 'temp', label: '温度', type: 'select', options: ['温かい', '冷たい'], default: '温かい' },
      ],
    },
    {
      id: 'item_006',
      category: 'noodle',
      name: 'パッタイ',
      description: '本場タイ風の甘辛焼きそば。えびとピーナッツ入り',
      price: 920,
      image: null,
      emoji: '🥘',
      popular: false,
      allergens: ['gluten', 'egg', 'shrimp', 'peanut', 'soy'],
      customizable: [
        { id: 'spice', label: '辛さ', type: 'select', options: ['なし', '少し辛め', '辛口'], default: 'なし' },
      ],
    },
    {
      id: 'item_007',
      category: 'side',
      name: 'シーザーサラダ',
      description: 'クリスピーベーコンとパルメザンチーズをたっぷり',
      price: 580,
      image: null,
      emoji: '🥗',
      popular: false,
      allergens: ['gluten', 'egg', 'dairy'],
      customizable: [],
    },
    {
      id: 'item_008',
      category: 'side',
      name: 'フライドポテト',
      description: 'サクサクに揚げた黄金ポテト。塩またはハーブ塩',
      price: 380,
      image: null,
      emoji: '🍟',
      popular: true,
      allergens: [],
      customizable: [
        { id: 'salt', label: 'シーズニング', type: 'select', options: ['塩', 'ハーブ塩', 'チーズ(+50円)'], default: '塩' },
      ],
    },
    {
      id: 'item_009',
      category: 'side',
      name: '枝豆',
      description: '国産枝豆を塩茹で。ビールのお供に',
      price: 280,
      image: null,
      emoji: '🫛',
      popular: false,
      allergens: ['soy'],
      customizable: [],
    },
    {
      id: 'item_010',
      category: 'drink',
      name: 'クラフトコーラ',
      description: 'スパイスを独自配合した自家製クラフトコーラ',
      price: 480,
      image: null,
      emoji: '🥤',
      popular: true,
      allergens: [],
      customizable: [
        { id: 'ice', label: '氷', type: 'select', options: ['氷あり', '氷なし', '氷少なめ'], default: '氷あり' },
      ],
    },
    {
      id: 'item_011',
      category: 'drink',
      name: '自家製レモネード',
      description: '国産レモンをその場で搾る生レモネード',
      price: 520,
      image: null,
      emoji: '🍋',
      popular: false,
      allergens: [],
      customizable: [
        { id: 'sweet', label: '甘さ', type: 'select', options: ['甘め', '普通', '甘さ控えめ'], default: '普通' },
        { id: 'sparkling', label: '炭酸', type: 'select', options: ['なし', '炭酸あり'], default: 'なし' },
      ],
    },
    {
      id: 'item_012',
      category: 'drink',
      name: '本日のコーヒー',
      description: '毎日変わるシングルオリジンのドリップコーヒー',
      price: 420,
      image: null,
      emoji: '☕',
      popular: false,
      allergens: ['dairy'],
      customizable: [
        { id: 'milk', label: 'ミルク', type: 'select', options: ['ブラック', 'ミルクあり', 'オーツミルク(+80円)'], default: 'ブラック' },
      ],
    },
    {
      id: 'item_013',
      category: 'dessert',
      name: '濃厚プリン',
      description: '卵黄たっぷりの昔ながらのかためプリン',
      price: 380,
      image: null,
      emoji: '🍮',
      popular: true,
      allergens: ['egg', 'dairy'],
      customizable: [],
    },
    {
      id: 'item_014',
      category: 'dessert',
      name: 'バスクチーズケーキ',
      description: 'とろける食感のバスク風チーズケーキ',
      price: 480,
      image: null,
      emoji: '🍰',
      popular: false,
      allergens: ['gluten', 'egg', 'dairy'],
      customizable: [],
    },
    {
      id: 'item_015',
      category: 'dessert',
      name: 'ソルベ(季節のフルーツ)',
      description: '本日の旬のフルーツを使ったノンデイリーソルベ',
      price: 350,
      image: null,
      emoji: '🍧',
      popular: false,
      allergens: [],
      customizable: [],
    },
  ],
};

window.MENU_DATA = MENU_DATA;
